export const USERS_LIST_FETCH_BEGIN = 'USERS_LIST_FETCH_BEGIN';
export const USERS_LIST_FETCH_SUCCESS = 'USERS_LIST_FETCH_SUCCESS';
export const USERS_LIST_FETCH_FAILURE = 'USERS_LIST_FETCH_FAILURE';
